TECH-6367-windows-provisioning-pip-version
counsyl/puppet-python pull request #10
Opened 2021-02-24 04:47 UTC by raj-wh

2021-02-24 14:14 UTC, jdavisp3 requested changes

2021-02-24 14:14 UTC, jdavisp3 commented on manifests/init.pp
> +
I would suggest we do this a bit differently.

1. Default a class variable called `easy_install_pip` that defaults to `pip`.
2. Make the `exec` block above use `command => "${easy_install} ${easy_install_pip}"`.

That way there's no change in behavior for this public package but we we can can the pip version via Hiera.

2021-02-25 05:39 UTC, raj-wh reviewed
Made pip a class variable

2021-02-25 14:11 UTC, jdavisp3 requested changes

2021-02-25 14:11 UTC, jdavisp3 commented on manifests/init.pp
> +  ${easy_install_pip} = 'pip',
```suggestion
  $easy_install_pip = 'pip',
```

When you declare a pip variable or use it outside of a string you don't use the `{}`. Braces are for string interpolation.

2021-03-01 18:58 UTC, jdavisp3 approved these changes
LGTM!

2021-03-01 19:09 UTC, raj-wh commented
@jdavisp3 I don't seem to have merge permission on this repo.

2021-03-02 01:25 UTC, merged